# Generated by Django 4.0.5 on 2022-06-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='age',
            new_name='industry',
        ),
    ]
