module.exports = [
    {
    name: 'Mallrats',
    img: 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F20%2F2015%2F10%2Fmallrats-01-435.jpg&q=60',
    type: 'Comedy',
    director: 'Kevin Smith',
    stars: 'kevin Smith, Jay Mewes, Jeff Anderson, Jason Lee, Shannen Doherty, Ben Affleck',
    rating: '8/10',
    inStock: true,
    reviews:'',
    },
    {
    name: 'Avengers End Game',
    img: 'https://play-lh.googleusercontent.com/-0ThDhMWcaGtY58Ch4t-IhNJtQqi5RHY3bxqul3ixjFf_0mDYLpYZCvzh-hA1B8Jg5cE',
    type: 'Action, Adventure, Drama',
    director: 'Anthony Russo, Joe Russo',
    stars: 'Robery Downy Jr, Chris Evans, Scarlett Johansson, Chris Hemsworth',
    rating: '9/10',
    inStock: true,
    reviews:'',
    },
    {
    name: 'Clerks 2',
    img: 'https://m.media-amazon.com/images/M/MV5BODg1MzY2NDY0OF5BMl5BanBnXkFtZTcwNDgyMzQzMQ@@._V1_FMjpg_UX1000_.jpg',
    type: 'Comedy',
    director: 'Kevin Smith',
    stars: 'kevin Smith, Jay Mewes, Jeff Anderson, Rosario Dawson',
    rating: '10/10',
    inStock: true,
    reviews:'',
    },
    {
    name: 'Sharknado',
    img: 'https://m.media-amazon.com/images/M/MV5BODcwZWFiNTEtNDgzMC00ZmE2LWExMzYtNzZhZDgzNDc5NDkyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg',
    type: 'Horror/Sci-Fi',
    director:"Anthony C. Ferrante",
    stars:"Ian Ziering, Tara Reid, and John Heard",
    rating: '2/10',
    inStock: true,
    reviews:'',
    },
    {
    name: 'Star Wars Episode VIII: The Last Jedi',
    img: 'https://m.media-amazon.com/images/I/81WjGytz7HL._SL1500_.jpg',
    type: 'Comedy',
    director:"Rian Jognson",
    stars:"Adam Driver, Carrie Fisher, and Mark Hamill",
    rating: '9/10',
    inStock: true,
    reviews:'',
    },
    {
		name: "Forrest Gump",
		img:"https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
		type:"Drama/Romance",
		director:"Robert Zemeckis",
		stars:"Tom Hanks, Robin Wright, and Gary Sinise",
		rating:"9/10",
		inStock: true,
        reviews:'',
	},
	{
		name:"Toy Story",		
        img:"https://www.filmandtvnow.com/wp-content/uploads/2014/11/Toy-Story-Characters1.jpg",
		type:"Family/Comedy",
		director:"John Lasseter",
		stars:"Tom Hanks, John Morris, and Tim Allen",
		rating:"8/10",
		inStock: true,
        reviews:'',
	},
	{
		name:"The Wizard of Oz",
		img:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/1458/1458078_so.jpg",
		type:"Musical/Fantasy",
		director:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/1458/1458078_so.jpg",
		stars:"Judy Garland, Ray Bolger, Jack Haley, Bert Lahr, and Margaret Hamilton",
		rating:"8/10",
		inStock: true,
        reviews:'',
	},
	{
		name:"The Emoji Movie",
		img:"https://m.media-amazon.com/images/M/MV5BMTkzMzM3OTM2Ml5BMl5BanBnXkFtZTgwMDM0NDU3MjI@._V1_FMjpg_UX1000_.jpg",
		type:"Family/Comedy",
		director:"Tony Leondis",
		stars:"TJ MIller, Anna Faris, and James Corden",
		rating:"4/10",
		inStock: true,
        reviews:'',
	},
	{
		name:"Disaster Movie",
		img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs2BfeyUmm6Q0l5or37PcOZdEL6DTkHmcDvllbUHil5ne4LJLx",
		type:"Comedy/Disaster",
		director:"Jason Friedberg",
		stars:"Matt Lanter, Vanessa Minnillo, and Kim Kardashian",
		rating:"2/10",
		inStock: true,
        reviews:'',
	}
]